const en = {
  app: {
    name: "MediaDetector",
  },

  header: {
    info: "Information",
    back: "Back"
  },

  sidebar: {
    actions: "Actions",
    newProject: "New Project",
    newPerson: "New Person",
    profanityDictionary: "Profanity Dictionary",
  },

  projects: {
    title: "Projects",
    loading: "Loading projects...",
    empty: "No projects yet.",
    created: "Created",
    error: "Failed to load projects.",
  },

  info: {
    title: "MediaDetector",
    description:
      "MediaDetector is an AI-assisted application for processing and analyzing video and audio files.",
    processing:
      "The application allows media files to be organized into projects and processed using independent modules.",
    about: "About the application",
    projectDescription:
      "Each project contains its own files and processing results. Individual AI modules can use the output generated by previous modules.",
    version: "Version",
    close: "Close",
  },

  footer: {
    contact: "Contact",
  },
  newProject: {
    title: "New Project",
    description: "Create a new project.",
    name: "Project name",
    placeholder: "Project name",
    required: "Project name is required.",
    cancel: "Cancel",
    create: "Create Project",
    creating: "Creating...",
    failed: "Failed to create project.",
  },

  profanityDictionary: {
    title: "Dictionary of Swear Words",
    description:
      "A global dictionary of words used when filtering content.",
    loading: "Loading dictionary...",
    loadError: "Failed to load dictionary.",
    saveError: "Failed to save dictionary.",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving...",
    saveDictionary: "Save Dictionary",
    back: "Back",
    placeholder: "Enter the word",
  },

  projectDetails: {
    loading: "Loading project...",
    project: "Project",
    files: "Project files",
    fileCount: "files",
    emptyFiles: "The project does not contain any files yet.",
    preview: "File preview",
    selectFile: "Select a file from the list above.",
    modules: "Modules",
    modulesComingSoon: "AI modules will be here.",
    open: "Open",
    download: "Download",
    delete: "Delete",
    back: "Back",
    downloadAll: "Download all files",
    deleteProject: "Delete project",
    deleteConfirmation:
      'Are you sure you want to delete project "{name}"?',
    loadError: "Failed to load the project.",
    deleteError: "Failed to delete the project.",
  },

  addSourceFile: {
    title: "Add source files",
    description: "Add source audio or video files to the project.",
    dropzone: {
      title: "Drag files here",
      description: "or click to select files from your computer",
      active: "Drop files here",
      supported: "Supported audio and video files",
    },
    selectedFiles: "Selected files",
    removeFile: "Remove file",
    upload: "Add files",
    uploading: "Adding...",
    error: {
      noProject: "Project not found.",
      noFiles: "Select at least one file.",
      upload: "Failed to add files.",
    },
    success: "Files have been added.",
  },

};

export default en;