const en = {
  app: {
    name: "MediaDetector",
  },

  header: {
    info: "Information",
  },

  sidebar: {
    actions: "Actions",
    newProject: "New Project",
    newPerson: "New Person",
    profanityDictionary: "Profanity Dictionary",
  },

  projects: {
    title: "Projects",
    loading: "Loading projects...",
    empty: "No projects yet.",
    created: "Created",
    error: "Failed to load projects.",
  },

  info: {
    title: "MediaDetector",
    description:
      "MediaDetector is an AI-assisted application for processing and analyzing video and audio files.",
    processing:
      "The application allows media files to be organized into projects and processed using independent modules.",
    about: "About the application",
    projectDescription:
      "Each project contains its own files and processing results. Individual AI modules can use the output generated by previous modules.",
    version: "Version",
    close: "Close",
  },

  footer: {
    contact: "Contact",
  },
  newProject: {
    title: "New Project",
    description: "Create a new project.",
    name: "Project name",
    placeholder: "Project name",
    required: "Project name is required.",
    cancel: "Cancel",
    create: "Create Project",
    creating: "Creating...",
    failed: "Failed to create project.",
  },

  profanityDictionary: {
    title: "Słownik przekleństw",
    description:
      "Globalny słownik słów używanych podczas filtrowania treści.",
    loading: "Ładowanie słownika...",
    loadError: "Nie udało się wczytać słownika.",
    saveError: "Nie udało się zapisać słownika.",
    add: "Dodaj",
    edit: "Edytuj",
    delete: "Usuń",
    save: "Zapisz",
    cancel: "Anuluj",
    saving: "Zapisywanie...",
    saveDictionary: "Zapisz słownik",
    back: "Powrót",
    placeholder: "Wpisz słowo",
  },
};

export default en;